version: '3'
services:
  flask:
    # Путь до Dockerfile
    build: ./app
    # Имя контейнера
    container_name: backend-flask
    # Создание переменных окружения в контейнере
    environment:
      # Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
    # Перезапускаем сервис в случае падения
    restart: on-failure
    # директория ./app, появится в директории контейнера /app
    volumes:
      - ./app:/app
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:5000"
    # Команда, которая будет выполнена после старта сервиса
    command: python main.py